landing for golos.io iOs app
GolosChain/mobile-app-landing pull request #1
Opened 2018-11-23 13:11 UTC by AlexRekish

2018-11-23 13:53 UTC, bacher requested changes

2018-11-23 13:53 UTC, Bacher commented on .editorconfig
> +trim_trailing_whitespace = false
+
```
[*.json]
indent_size = 2
```

2018-11-23 13:53 UTC, Bacher commented on .gitignore
> +/**/package-lock.json
`package-lock.json` надо добавить в репозиторий

2018-11-23 13:53 UTC, Bacher commented on package.json
> +    "author": "Aliaksei Rekish",
Лучше указать `Golos.io Team`

2018-11-23 13:53 UTC, Bacher commented on src/_templates/modal.pug
> +    img(src="img/logo/email.svg", alt="").modal__icon
Пустые `alt=""` лучше не оставлять, лучше потом добавим если нужно будет.

2018-11-23 13:53 UTC, Bacher commented on src/img/logo/btn-ios.svg
> +</svg>
Все svg файлы надо прогнать через `svgo` и прям сохранить в репозиторий.

2018-11-23 13:53 UTC, Bacher commented on src/index.pug
> +        // Template Basic Images End
Убрать эти комментарии, смысла нет в них для нас.

2018-11-23 13:53 UTC, Bacher commented on src/index.pug
> +            a.logo__wrapper(href="https://golos.io" target="_blank" rel="noreferrer")
На этой ссылке `rel="noreferrer"` стоит наверное убрать, так как ресурс как раз наш.

2018-11-23 13:53 UTC, Bacher commented on src/index.pug
> +                            img(src=`img/logo/icon-instr-${index + 1}.svg`, alt=`Иконка '${val}'` width="76" height="76")
```
alt=`Иконка '${val}'`
```
Нужна локализация.

2018-11-23 13:53 UTC, Bacher commented on src/js/input.js
> +    } else xStart = null;
в if и else код должен быть в {   }

```
} else {
    xStart = null;
}
```

2018-11-23 13:53 UTC, Bacher commented on src/locales/EN.json
> +    "second_locale": "ru",
Как странно сделано second_locale.

Что будет если добавится еще 1 язык? Украинский может вполне добавиться.
Придется во всех файлах добавлять.

2018-11-23 13:53 UTC, Bacher commented on src/sass/blocks/android-reviews.sass
> +        &:not(:nth-child(5))
Указывать конкретный номер элемента плохая затея.
Если добавиться элемент карусели?

2018-11-23 13:53 UTC, Bacher commented on src/sass/blocks/android-reviews.sass
> +        &:nth-child(5)
Тоже.

2018-11-23 13:53 UTC, Bacher commented on src/sass/main.sass
> +@import	"normalize"
Пробелы?

2018-11-23 13:53 UTC, Bacher commented on src/sass/normalize.css
> +  font-family: monospace, monospace; /* 1 */
Тут явно ошибка, дублирование.

2018-11-23 14:00 UTC, Bacher commented
1. Надо добавить favicon

2. Меняется ширина при открытии меню + надо выставить `user-select: none;`
![image](https://user-images.githubusercontent.com/2598671/48946952-7e41ff80-ef40-11e8-81ba-2a6bf7002019.png)

3. Тут явно неправильная тень (мне кажется, не уверен):
![image](https://user-images.githubusercontent.com/2598671/48946985-a3367280-ef40-11e8-8db2-2dcc5bd5d090.png)

4. Слишком маленький отступ (не как на дизайне):
![image](https://user-images.githubusercontent.com/2598671/48947017-c06b4100-ef40-11e8-89c1-cb12278b6832.png)

5. Тени не должны быть в картинках, надо добавлять уже в браузере (box-shadow):
![image](https://user-images.githubusercontent.com/2598671/48947065-eb559500-ef40-11e8-91f1-a89ae6e1ae82.png)

6. Пережато (можно попросить Аллу убрать тень вообще, если сжатие не настраивается):
![image](https://user-images.githubusercontent.com/2598671/48947072-f5779380-ef40-11e8-8142-49b3bd41591d.png)

7. Тень не как на дизайне:
![image](https://user-images.githubusercontent.com/2598671/48947109-1b049d00-ef41-11e8-8887-117a16e20d87.png)

8. Не стоит брать svg для этих картинок, оно плохо выравнивается (лучше сверстать с помощью border-radius: 50%:
![image](https://user-images.githubusercontent.com/2598671/48947143-3a032f00-ef41-11e8-8e1d-43be4804f5b0.png)

2018-11-23 14:01 UTC, Bacher commented
Поставить `user-select: none;` всем элементами которые подразумевают активность по клику:
![image](https://user-images.githubusercontent.com/2598671/48947190-64ed8300-ef41-11e8-8739-2c795c2a3f1b.png)

2018-11-23 14:03 UTC, bacher requested changes

2018-11-23 14:03 UTC, Bacher commented on src/index.pug
> +                            input.be-in-touch__email(type="email" id="email-field" placeholder="Email" required)
Добавить атрибуты
`autocorrect="off" autocapitalize="off" spellcheck="false"`

2018-11-23 14:04 UTC, Bacher commented
Отступ до текста сверху должен быть больше чем до текста снизу.

![image](https://user-images.githubusercontent.com/2598671/48947326-cf9ebe80-ef41-11e8-99b3-7ee0947ba84f.png)

2018-11-23 14:06 UTC, Bacher commented
Не работают переходы в десктопной версии.

![image](https://user-images.githubusercontent.com/2598671/48947400-1b516800-ef42-11e8-87bf-1d2683f55202.png)

2018-11-23 14:07 UTC, Bacher commented
Звездочки уезжают

![image](https://user-images.githubusercontent.com/2598671/48947428-315f2880-ef42-11e8-952a-98f5cc794b29.png)

2018-11-23 14:07 UTC, Bacher commented
Не работает смена языка:
![image](https://user-images.githubusercontent.com/2598671/48947445-420f9e80-ef42-11e8-98b2-eb3ca24bcfcf.png)

2018-11-27 13:59 UTC, bacher approved these changes

2018-12-05 12:17 UTC, b1acksun approved these changes

2018-12-06 09:46 UTC, merged

2022-12-23 00:49 UTC, Nilmerg666 reviewed
Go